export enum OrderStatus {
  PENDING = "PENDING",
  STOCK_RESERVING = "STOCK_RESERVING",
  STOCK_RESERVED = "STOCK_RESERVED",
  PAYMENT_PROCESSING = "PAYMENT_PROCESSING",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
}

export enum OrderFailureReason {
  STOCK_UNAVAILABLE = "STOCK_UNAVAILABLE",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK",
}
